USE ERP;
SELECT SUM(VALOR) AS TOTAL FROM PEDIDOSMANUTENCOES;
SELECT AVG(VALOR) AS MEDIA FROM PEDIDOSMANUTENCOES;
SELECT SUM(VALOR) AS TOTAL_COMPRAS FROM PEDIDOSCOMPRAS;
SELECT AVG(VALOR) AS MEDIA FROM PEDIDOSCOMPRAS;
SELECT MAX(VALOR) AS PRECO_MAX FROM PEDIDOSMANUTENCOES;
SELECT MIN(VALOR) AS PRECO_MIN FROM PEDIDOSMANUTENCOES;
SELECT MAX(VALOR) AS PRECO_COMPRA_MAX FROM PEDIDOSCOMPRAS;
SELECT MIN(VALOR) AS PRECO_COMPRA_MIN FROM PEDIDOSCOMPRAS;

SELECT * FROM CLIENTES WHERE TELEFONE LIKE '(96) %';
SELECT * FROM CLIENTES WHERE TELEFONE LIKE '%3';

SELECT * FROM FUNCIONARIOS WHERE ID IN (SELECT FUNCIONARIO FROM TECNICOS WHERE CNH IS NULL);
SELECT * FROM FUNCIONARIOS WHERE ID IN (SELECT FUNCIONARIO FROM TECNICOS WHERE CNH IS NOT NULL);

SELECT COUNT(*) FROM SUPORTEONLINE WHERE Data LIKE '_____03%';
-- SELECT COUNT(*) FROM SUPORTEONLINE WHERE MONTH(DATA)= 3; -- OUTRA FORMA DE RESOLVER CONSIDERADA MELHOR 

SELECT DISTINCT CLIENTE FROM PEDIDOSMANUTENCOES;
-- SELECT DISTINCT CLI.NOME AS NOME_CLIENTE FROM CLIENTES AS CLI, PEDIDOSMANUTENCOES AS PEDIDOS WHERE PEDIDOS.CLIENTE = CLI.ID; -- OUTRA FORMA DE RESOLVER CONSIDERADA MELHOR
SELECT * FROM CLIENTES WHERE ID NOT IN (SELECT CLIENTE FROM PEDIDOSMANUTENCOES);-- NÃO CONSEGUI FAZER OS CLIENTES QUE NUNCA COMPRARAM

SELECT DISTINCT CLIENTE FROM PEDIDOSCOMPRAS;
SELECT * FROM cliente WHERE id IN (SELECT cliente FROM pedidoscompras); -- OUTRA FORMA DE RESOLVER CONSIDERADA MELHOR
SELECT * FROM CLIENTES WHERE ID NOT IN (SELECT CLIENTE FROM PEDIDOSCOMPRAS);

SELECT DISTINCT ATENDENTEONLINE FROM SUPORTEONLINE WHERE Data LIKE '_____11%';
SELECT * FROM FUNCIONARIOS WHERE ID IN (SELECT FUNCIONARIO FROM ATENDENTESONLINE WHERE ID IN ( SELECT ATENDENTEONLINE FROM SUPORTEONLINE WHERE MONTH(DATA) = 11)); -- OUTRA FORMA DE RESOLVER 