-- Vendedor que mais realizou atendimentos a clientes de pedidos de compras e valor total
SELECT L.ID, F.NOME, F.CPF, SUM(PC.VALOR) AS VALOR_PEDIDOS, COUNT(L.ID) as Atendimentos FROM FUNCIONARIOS F 
	JOIN LOGISTAS L ON L.FUNCIONARIO = F.ID
    JOIN PEDIDOSCOMPRAS PC ON PC.LOGISTA = L.ID
GROUP BY L.ID
ORDER BY COUNT(L.ID)
LIMIT 1;

-- Qual foi o fornecedor que atendeu a mais requisições e a qtde
SELECT R.ID, F.NOME, SUM(QUANTIDADE) AS QUANTIDADE, COUNT(F.ID) AS ID_FORNECEDOR 
FROM FORNECEDORES F 
	JOIN REQUISITCOES R ON R.FORNECEDOR = F.ID
GROUP BY F.ID
ORDER BY COUNT(F.ID) DESC
LIMIT 1;